# Generated by Django 4.0.6 on 2022-08-26 02:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='comments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='auto',
            name='make',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autos.make'),
        ),
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='nickname',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')]),
        ),
        migrations.AddField(
            model_name='make',
            name='name',
            field=models.CharField(default='', help_text='Enter a make (e.g. Dodge)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
