# Generated by Django 4.0.6 on 2022-08-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_comments_auto_make_auto_mileage_auto_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
