# Generated by Django 4.0.6 on 2022-08-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_alter_auto_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='mileage',
        ),
    ]
