# Generated by Django 4.0.6 on 2022-08-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_remove_auto_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
