# Generated by Django 4.0.6 on 2022-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_alter_auto_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
    ]
